{% set name = "napari-validate-random-label-predictions" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-validate-random-label-predictions-{{ version }}.tar.gz
  sha256: 11a3578ee936ae5414c6a8bbd92e42aa3395a2c6fafcd4886311031bc140ff9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8,<3.11
    - qtpy
    - scikit-image

test:
  imports:
    - napari_validate_random_label_predictions
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gatoniel/napari-validate-random-label-predictions
  summary: Validate separate instances of label predictions manually
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
